
common: &COMMON
  encoding: utf8
  pool: 5
  timeout: 5000
  adapter: mysql2
  host: localhost
  user: root

production:
  <<: *COMMON
  database: nabu

uat:
  <<: *COMMON
  database: nabu

development:
  <<: *COMMON
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *COMMON
  adapter: sqlite3
  database: db/test.sqlite3
  verbosity: quiet
