
common: &COMMON
  encoding: utf8
  pool: 5
  timeout: 5000
  adapter: mysql2
  host: localhost
  username: root

production:
  <<: *COMMON
  database: nabu

staging:
  <<: *COMMON
  database: nabu_staging
  username: nabu

development:
  <<: *COMMON
  database: nabu_devel

test:
  <<: *COMMON
  database: nabu_test
  verbosity: quiet
